export const singin= 'Sing In'
export const review = 'Review'
export const signup  = 'Sign Up'
export const myView ='My View'
export const lastestRepo = 'Lastest Repository'
export const highestRate = 'Highest Rate'
export const lowestRate = 'Lowest Rate'
